### ISSUE TITLE
V-76759 doesn't need to check against all TLS & SSL versions

### ISSUE THREAD

**Issue by HackerShark** [mitre/microsoft-iis-8.5-server-stig-baseline#24]
Currently the control checks every single version of TLS and SSL in the registry. This can be enhanced by checking if the registry entry exists first before running the control. This eliminates unnecessary control failures.

**Comment by HackerShark** [comment]
Pull request #28 created for this fix.

**Comment by Amndeep7** [comment]
Rony's review makes it seem that all registry entries are required: https://github.com/mitre/microsoft-iis-8.5-server-stig-baseline/pull/28#issuecomment-450234305

Please reopen if this is not the case @HackerShark
