### ISSUE TITLE
Check Text fix text mismatch

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-iis-8.5-server-stig-baseline#33]
https://github.com/mitre/stig-microsoft-iis-8.5-server-baseline/blob/aafcd00a9243f1912447bc69df8d0d64acaead26/controls/V-76687.rb#L116

Fix text direct with incomplete guidance adding:
```
 Click on the \"Source Type\" drop-down list and select \"Server Variable\".
  Click “OK” to add.
```

*but check text does not ask to check for that field*

and earlier version of the directs as below:
```
Click on the "Source Type" drop-down list and select "Server Variable".
Click on the "Source" drop-down list and select "HTTP_CONNECTION".
Click OK to add.
```
if Server Variable is to added the check must be modified as below to follow the same pattern as the rest

```    
it { should match /sourceName\s+:\s+HTTP_CONNECTION\s+sourceType\s+:\s+ServerVariable/ }
```

**Comment by georgedias** [comment]
Control requirements were modified, this OBE
