### ISSUE TITLE
Refrain from using Rspec style expect() syntax

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-iis-8.5-server-stig-baseline#35]
The use of underlying rspec style expect() results in errors similar to:
```
Message: undefined method `expect' for #<RSpec::ExampleGroups::AnIIS85WebServerMustMaintainTheConfidentialityOfControlledInformationDuringTransmissionThroughTheUseOfAnApprovedTLSVersionTLS11ShouldNotBeDisabledByDefaultCurrentlyTLS11DisabledByDefault:0x0000000008e6c1e0>
Did you mean? exec
```

We should refrain from this style since this is not officially supported by inspec

Affected controls:

V-76759
V-76769
V-76771
V-76761
V-76757

**Comment by aaronlippold** [comment]
This should be fixed by 3.0.61

**Comment by Amndeep7** [comment]
Has this syntax issue been resolved in inspec yet?  If so, this issue can be closed.

**Comment by georgedias** [comment]
No longer an issue
